// <auto-generated />
using System;
using Khyout.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Khyout.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260929074745_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Khyout.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_en");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_categories_slug");

                    b.HasIndex("ParentId", "SortOrder")
                        .HasDatabaseName("ix_categories_parent_sort");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000001"),
                            IsActive = true,
                            NameAr = "أقمشة قطنية",
                            NameEn = "Cotton Fabrics",
                            Slug = "cotton-fabrics",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000002"),
                            IsActive = true,
                            NameAr = "أقمشة تريكو",
                            NameEn = "Knitted Fabrics",
                            Slug = "knitted-fabrics",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000003"),
                            IsActive = true,
                            NameAr = "دنيم",
                            NameEn = "Denim",
                            Slug = "denim",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000004"),
                            IsActive = true,
                            NameAr = "أقمشة صوفية",
                            NameEn = "Wool Fabrics",
                            Slug = "wool-fabrics",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000005"),
                            IsActive = true,
                            NameAr = "أقمشة صناعية",
                            NameEn = "Synthetic Fabrics",
                            Slug = "synthetic-fabrics",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000006"),
                            IsActive = true,
                            NameAr = "فيسكوز وحرير صناعي",
                            NameEn = "Viscose & Rayon",
                            Slug = "viscose-rayon",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000007"),
                            IsActive = true,
                            NameAr = "أقمشة مخلوطة",
                            NameEn = "Blended Fabrics",
                            Slug = "blended-fabrics",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000008"),
                            IsActive = true,
                            NameAr = "كتان",
                            NameEn = "Linen",
                            Slug = "linen",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000009"),
                            IsActive = true,
                            NameAr = "خيوط قطنية",
                            NameEn = "Cotton Yarn",
                            Slug = "cotton-yarn",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-00000000000a"),
                            IsActive = true,
                            NameAr = "خيوط صناعية",
                            NameEn = "Synthetic Yarn",
                            Slug = "synthetic-yarn",
                            SortOrder = 10
                        });
                });

            modelBuilder.Entity("Khyout.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("address");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LogoPath")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("logo_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("verification_status");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.Property<Guid?>("VerifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("verified_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("City")
                        .HasDatabaseName("ix_companies_city");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_companies_name");

                    b.HasIndex("VerificationStatus")
                        .HasDatabaseName("ix_companies_verification_status");

                    b.HasIndex("VerifiedByUserId");

                    b.ToTable("companies", null, t =>
                        {
                            t.HasCheckConstraint("ck_companies_type", "type IN ('Buyer', 'Supplier')");

                            t.HasCheckConstraint("ck_companies_verification_status", "verification_status IN ('Pending', 'Verified', 'Rejected')");
                        });
                });

            modelBuilder.Entity("Khyout.Domain.Entities.FabricAttributes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CareNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("care_notes");

                    b.Property<string>("ColorFamily")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("color_family");

                    b.Property<int>("Gsm")
                        .HasColumnType("integer")
                        .HasColumnName("gsm");

                    b.Property<int>("GsmTolerancePct")
                        .HasColumnType("integer")
                        .HasColumnName("gsm_tolerance_pct");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("WeaveStructure")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("weave_structure");

                    b.Property<int?>("WeightPerMeterG")
                        .HasColumnType("integer")
                        .HasColumnName("weight_per_meter_g");

                    b.Property<int>("WidthCm")
                        .HasColumnType("integer")
                        .HasColumnName("width_cm");

                    b.HasKey("Id");

                    b.HasIndex("Gsm")
                        .HasDatabaseName("ix_fabric_attributes_gsm");

                    b.HasIndex("ProductId")
                        .IsUnique()
                        .HasDatabaseName("ux_fabric_attributes_product_id");

                    b.HasIndex("WeaveStructure")
                        .HasDatabaseName("ix_fabric_attributes_weave_structure");

                    b.ToTable("fabric_attributes", null, t =>
                        {
                            t.HasCheckConstraint("ck_fabric_attributes_gsm", "gsm > 0");

                            t.HasCheckConstraint("ck_fabric_attributes_gsm_tolerance", "gsm_tolerance_pct BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_fabric_attributes_weave", "weave_structure IN ('Plain', 'Twill', 'Satin', 'Knit', 'Denim')");

                            t.HasCheckConstraint("ck_fabric_attributes_width", "width_cm > 0");
                        });
                });

            modelBuilder.Entity("Khyout.Domain.Entities.FabricComposition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FiberType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("fiber_type");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("percentage");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.HasKey("Id");

                    b.HasIndex("FiberType", "Percentage")
                        .HasDatabaseName("ix_fabric_composition_fiber_percentage");

                    b.HasIndex("ProductId", "FiberType")
                        .IsUnique()
                        .HasDatabaseName("ux_fabric_composition_product_fiber");

                    b.ToTable("fabric_composition", null, t =>
                        {
                            t.HasCheckConstraint("ck_fabric_composition_percentage", "percentage BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("Khyout.Domain.Entities.OtpCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("AttemptsMade")
                        .HasColumnType("smallint")
                        .HasColumnName("attempts_made");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("purpose");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_otp_codes_expires_at");

                    b.HasIndex("PhoneNumber", "Purpose", "ExpiresAt")
                        .HasDatabaseName("ix_otp_codes_lookup");

                    b.ToTable("otp_codes", null, t =>
                        {
                            t.HasCheckConstraint("ck_otp_codes_attempts", "attempts_made >= 0");

                            t.HasCheckConstraint("ck_otp_codes_purpose", "purpose IN ('Login', 'Onboarding')");
                        });
                });

            modelBuilder.Entity("Khyout.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("Attempts")
                        .HasColumnType("smallint")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TargetRef")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("target_ref");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_outbox_messages_created_at");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("ix_outbox_messages_dispatch");

                    b.ToTable("outbox_messages", null, t =>
                        {
                            t.HasCheckConstraint("ck_outbox_messages_attempts", "attempts >= 0");

                            t.HasCheckConstraint("ck_outbox_messages_status", "status IN ('Pending', 'Sent', 'Failed')");

                            t.HasCheckConstraint("ck_outbox_messages_type", "type IN ('RfqCreated', 'QuotationSubmitted', 'QuotationAccepted', 'QuotationRejected', 'QuotationExpired', 'SampleRequested', 'SampleStatusChanged')");
                        });
                });

            modelBuilder.Entity("Khyout.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal?>("IndicativePrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("indicative_price");

                    b.Property<decimal>("Moq")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("moq");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("SupplierCompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_company_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit_of_measure");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Moq")
                        .HasDatabaseName("ix_products_moq");

                    b.HasIndex("SupplierCompanyId")
                        .HasDatabaseName("ix_products_supplier_company_id");

                    b.HasIndex("CategoryId", "Status", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_products_category_status_created");

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("ck_products_moq", "moq > 0");

                            t.HasCheckConstraint("ck_products_status", "status IN ('Draft', 'Active', 'Archived')");

                            t.HasCheckConstraint("ck_products_unit", "unit_of_measure IN ('Meter', 'Kg', 'Roll', 'Yard')");
                        });
                });

            modelBuilder.Entity("Khyout.Domain.Entities.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<int>("HeightPx")
                        .HasColumnType("integer")
                        .HasColumnName("height_px");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("SizeBytes")
                        .HasColumnType("integer")
                        .HasColumnName("size_bytes");

                    b.Property<short>("SortOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("sort_order");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("storage_path");

                    b.Property<int>("WidthPx")
                        .HasColumnType("integer")
                        .HasColumnName("width_px");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .IsUnique()
                        .HasDatabaseName("ux_product_images_content_hash");

                    b.HasIndex("ProductId", "SortOrder")
                        .HasDatabaseName("ix_product_images_product_sort");

                    b.ToTable("product_images", null, t =>
                        {
                            t.HasCheckConstraint("ck_product_images_dimensions", "width_px > 0 AND height_px > 0 AND size_bytes > 0");
                        });
                });

            modelBuilder.Entity("Khyout.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_expires_at");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Khyout.Domain.Entities.RfqQuotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<int>("LeadTimeDays")
                        .HasColumnType("integer")
                        .HasColumnName("lead_time_days");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("note");

                    b.Property<Guid>("RfqRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("rfq_request_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("SupplierCompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_company_id");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.HasKey("Id");

                    b.HasIndex("RfqRequestId", "Status")
                        .HasDatabaseName("ix_rfq_quotations_rfq_status");

                    b.HasIndex("RfqRequestId", "SupplierCompanyId")
                        .IsUnique()
                        .HasDatabaseName("ux_rfq_quotations_rfq_supplier");

                    b.HasIndex("SupplierCompanyId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_rfq_quotations_supplier_created");

                    b.HasIndex("ValidUntil", "Status")
                        .HasDatabaseName("ix_rfq_quotations_valid_until_status");

                    b.ToTable("rfq_quotations", null, t =>
                        {
                            t.HasCheckConstraint("ck_rfq_quotations_lead_time", "lead_time_days >= 0");

                            t.HasCheckConstraint("ck_rfq_quotations_price", "unit_price > 0");

                            t.HasCheckConstraint("ck_rfq_quotations_status", "status IN ('Submitted', 'Accepted', 'Rejected', 'Expired', 'Withdrawn')");
                        });
                });

            modelBuilder.Entity("Khyout.Domain.Entities.RfqRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AcceptedQuotationId")
                        .HasColumnType("uuid")
                        .HasColumnName("accepted_quotation_id");

                    b.Property<Guid>("BuyerCompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_company_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("ClosingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closing_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<decimal>("QuantityNeeded")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("quantity_needed");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateOnly>("TargetDeliveryDate")
                        .HasColumnType("date")
                        .HasColumnName("target_delivery_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit_of_measure");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedQuotationId");

                    b.HasIndex("BuyerCompanyId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_rfq_requests_buyer_created");

                    b.HasIndex("CategoryId", "Status")
                        .HasDatabaseName("ix_rfq_requests_category_status");

                    b.HasIndex("Status", "ClosingDate")
                        .HasDatabaseName("ix_rfq_requests_status_closing");

                    b.ToTable("rfq_requests", null, t =>
                        {
                            t.HasCheckConstraint("ck_rfq_requests_quantity", "quantity_needed > 0");

                            t.HasCheckConstraint("ck_rfq_requests_status", "status IN ('Open', 'Awarded', 'Cancelled', 'Expired')");
                        });
                });

            modelBuilder.Entity("Khyout.Domain.Entities.SampleRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BuyerCompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeliveryCity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("delivery_city");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("quantity");

                    b.Property<Guid?>("RfqQuotationId")
                        .HasColumnType("uuid")
                        .HasColumnName("rfq_quotation_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("SupplierCompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_company_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("RfqQuotationId");

                    b.HasIndex("BuyerCompanyId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_sample_requests_buyer_created");

                    b.HasIndex("SupplierCompanyId", "Status")
                        .HasDatabaseName("ix_sample_requests_supplier_status");

                    b.ToTable("sample_requests", null, t =>
                        {
                            t.HasCheckConstraint("ck_sample_requests_quantity", "quantity > 0");

                            t.HasCheckConstraint("ck_sample_requests_status", "status IN ('Requested', 'Approved', 'Shipped', 'Received', 'Rejected')");
                        });
                });

            modelBuilder.Entity("Khyout.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_users_company_id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_users_phone_number");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_users_role");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_role", "role IN ('Buyer', 'Supplier', 'Admin')");
                        });
                });

            modelBuilder.Entity("Khyout.Domain.Entities.Category", b =>
                {
                    b.HasOne("Khyout.Domain.Entities.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Khyout.Domain.Entities.Company", b =>
                {
                    b.HasOne("Khyout.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("VerifiedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Khyout.Domain.Entities.FabricAttributes", b =>
                {
                    b.HasOne("Khyout.Domain.Entities.Product", "Product")
                        .WithOne("Attributes")
                        .HasForeignKey("Khyout.Domain.Entities.FabricAttributes", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Khyout.Domain.Entities.FabricComposition", b =>
                {
                    b.HasOne("Khyout.Domain.Entities.Product", "Product")
                        .WithMany("Composition")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Khyout.Domain.Entities.Product", b =>
                {
                    b.HasOne("Khyout.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Khyout.Domain.Entities.Company", "SupplierCompany")
                        .WithMany()
                        .HasForeignKey("SupplierCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("SupplierCompany");
                });

            modelBuilder.Entity("Khyout.Domain.Entities.ProductImage", b =>
                {
                    b.HasOne("Khyout.Domain.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Khyout.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Khyout.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Khyout.Domain.Entities.RfqQuotation", b =>
                {
                    b.HasOne("Khyout.Domain.Entities.RfqRequest", "RfqRequest")
                        .WithMany("Quotations")
                        .HasForeignKey("RfqRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Khyout.Domain.Entities.Company", "SupplierCompany")
                        .WithMany()
                        .HasForeignKey("SupplierCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RfqRequest");

                    b.Navigation("SupplierCompany");
                });

            modelBuilder.Entity("Khyout.Domain.Entities.RfqRequest", b =>
                {
                    b.HasOne("Khyout.Domain.Entities.RfqQuotation", "AcceptedQuotation")
                        .WithMany()
                        .HasForeignKey("AcceptedQuotationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Khyout.Domain.Entities.Company", "BuyerCompany")
                        .WithMany()
                        .HasForeignKey("BuyerCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Khyout.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcceptedQuotation");

                    b.Navigation("BuyerCompany");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Khyout.Domain.Entities.SampleRequest", b =>
                {
                    b.HasOne("Khyout.Domain.Entities.Company", "BuyerCompany")
                        .WithMany()
                        .HasForeignKey("BuyerCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Khyout.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Khyout.Domain.Entities.RfqQuotation", "RfqQuotation")
                        .WithMany()
                        .HasForeignKey("RfqQuotationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Khyout.Domain.Entities.Company", "SupplierCompany")
                        .WithMany()
                        .HasForeignKey("SupplierCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BuyerCompany");

                    b.Navigation("Product");

                    b.Navigation("RfqQuotation");

                    b.Navigation("SupplierCompany");
                });

            modelBuilder.Entity("Khyout.Domain.Entities.User", b =>
                {
                    b.HasOne("Khyout.Domain.Entities.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Khyout.Domain.Entities.Category", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Khyout.Domain.Entities.Company", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Khyout.Domain.Entities.Product", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Composition");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("Khyout.Domain.Entities.RfqRequest", b =>
                {
                    b.Navigation("Quotations");
                });
#pragma warning restore 612, 618
        }
    }
}
